# This is a basic workflow to help you get started with Actions

name: Build MKdocs and Deploy to S3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checks-out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
  
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: Install MKdocs
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install mkdocs-material
        python3 -m pip install mkdocs-git-revision-date-localized-plugin
    
    - name: Build site
      run: mkdocs build
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to S3
      run: cd site/ && aws s3 sync . s3://${{secrets.AWS_S3_BUCKET}} --only-show-errors
